name: stor_remote

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  supabase_flutter: ^1.5.0
  get_it: ^7.2.0
  json_annotation: ^4.8.0

  # domain:
  kern_domain:
    path: ../kern_domain

  # repositories:
  repo_watch:
    path: ../repo_watch
  repo_scan_history:
    path: ../repo_scan_history

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: ^6.6.1

