arb-dir: lib/src/l10n
template-arb-file: messages_uk.arb
output-localization-file: watch_scanner_localizations.dart
output-class: WatchScannerLocalizations
synthetic-package: false
nullable-getter: false