name: feat_watch_scanner

version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  camera: ^0.10.3+2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.2
  intl: ^0.17.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_mlkit_object_detection: ^0.6.0
  path: ^1.8.2
  path_provider: ^2.0.13
  url_launcher: ^6.1.10

  ui_lib:
    path: ../ui_lib

  kern_domain:
    path: ../kern_domain


dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/ml_models/
    - assets/images/