name: repo_scan_history

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  get_it: ^7.2.0


  #domain:
  kern_domain:
    path: ../kern_domain

  #stor_remote:
  stor_remote:
    path: ../stor_remote

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

