name: kern_domain

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  rxdart: ^0.27.7
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
  freezed: ^2.3.2

